
service: serverless-api
# app and org for use with dashboard.serverless.com
app: serverless-api
org: sebasdf11

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  region: us-east-1 #change it for your aws region

functions:
  manager:
    handler: handler.manage_request
    description: function that manages the request from the current queue
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - MainQueue
              - Arn
    deadLetter:
      targetArn:
        GetResourceArn: DLQueue

resources:
  Resources:
    MainQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "MainQueue"
        RedrivePolicy:
          deadLetterTargetArn:
            Fn::GetAtt:
            - "DLQueue"
            - "Arn"
          maxReceiveCount: 5

    DLQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: "DLQueue"



