
service: serverless-api
# app and org for use with dashboard.serverless.com
app: serverless-api
org: #your organization

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  region: us-east-1 #change it for your aws region
  enviorment:
    REGION: ${self:provider.region}

functions:
  manage-request:
    handler: handler.manage_request
    description: function that manages the http request from the api
    events:
      - http:
          method: post
          path: users
      - http:
          method: get
          path: users
      - http:
          method: patch
          path: users

