
service: serverless-api
# app and org for use with dashboard.serverless.com
app: serverless-api
org: sebasdf11

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  region: us-east-1 #change it for your aws region

functions:
  manager:
    handler: handler.manage_request
    description: function that manages the request from the current queue
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - MyQueue
              - Arn

resources:
  Resources:
    MyQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "MyQueue"


